name: CI pipeline for Todo app

on:
  push:
    branches: [main]

  workflow_dispatch:


jobs:
  FrontendBuild:
    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
      
      - name: build
        run: npm run build

  BackendBuildAndApiTests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout to Code
        uses: actions/checkout@v4
      
      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Install newman
        run: npm install -g newman

      - name: Install HTML reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Install dependencies
        run: npm ci

      - name: Inject env file
        run: |
          echo "PORT=${{secrets.PORT}}">>.env
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}">>.env
          echo "MONGO_URL=${{secrets.MONGO_URL}}">>.env

      - name: Start the backend server
        run: npm run start &

      - name: Wait for the backend to start
        run: npx wait-on http://localhost:${{secrets.PORT}}/health

      - name: Run the api-scripts
        run: newman run ../api-tests/Todo.postman_collection.json -e ../api-tests/variables.json -r cli,htmlextra

      - run: find ./newman -type f
      - name: Store the API results to github artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PostManResults
          path: server/newman/*.html
          if-no-files-found: error

        
